
# ========================================数据集===================================
DataSet:
  size: [224,224]  # 训练尺寸
  batch: 8
 
# ========================================模型===================================
Models: 
  checkpoint: None     # 权重路径 
  